services:
  postgres:
    image: postgres:15
    container_name: time-tracker-db
    environment:
      POSTGRES_DB: time-tracker
      POSTGRES_USER: time-tracker
      POSTGRES_PASSWORD: time-tracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U time-tracker"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: