package nicolfo.backend.dto

import java.time.LocalDateTime

data class TaskSummaryDTO (
    val startTime: LocalDateTime,
    val endTime: LocalDateTime,
    val duration: Long, // duration in minutes
    val autogeneratedStart: Boolean,
    val autogeneratedStop: Boolean,
)