// Types for the time tracking API responses

export type Action = 'START' | 'STOP';

export interface TimestampDTO {
  timestamp?: string;
  action?: Action;
}

export interface CurrentStatusDTO {
  isTaskRunning: boolean;
  duration?: number; // duration in minutes
  startTime?: string;
}

export interface TaskSummaryDTO {
  startTime: string;
  endTime: string;
  duration: number; // duration in minutes
  autogeneratedStart: boolean;
  autogeneratedStop: boolean;
}

export interface DailySummaryDTO {
  date: string;
  totalMinutes: number;
  tasks: TaskSummaryDTO[];
}

export interface WeeklySummaryDTO {
  totalMinutes: number;
  dailySummaries: DailySummaryDTO[];
}

export interface UserInfoDTO {
  username: string;
}